### ISSUE TITLE
Should the error message about adding a starting point disappear after adding a starting point?

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#48]
![image](https://user-images.githubusercontent.com/2707285/126547779-7714fd56-7522-4fd7-bee7-1d8cc523c224.png)

I click run without a starting point
get the error message
add location - error should go away

**Comment by avezina** [comment]
Or it goes away when click run and there is a starting point? User can press X to close it at any point to dismiss it.
Looks like the Directions widget handles it the way you describe it Mike, the error disappears once it's resolved. 
![image](https://user-images.githubusercontent.com/50338557/126551941-6dcbef22-f303-432c-b0ce-32f352b77d49.png)

**Comment by previnWong** [comment]
addressed in latest commit, please pull and verify.

**Comment by avezina** [comment]
Looks good

**Comment by MikeMillerGIS** [comment]
I could not verify this, the message is still there

**Comment by avezina** [comment]
@MikeMillerGIS perhaps you're still seeing the trace operation warning?
![2021-07-23_11-14-15](https://user-images.githubusercontent.com/50338557/126824229-05a690ad-36a1-4aa3-854f-8ec7b5e63e7b.gif)

**Comment by MikeMillerGIS** [comment]
verified
